.\" manual page [] for storectl version 0.1
.Dd August 15, 2016
.Dt STORECTL 8
.Os STORECTL 0.1
.Sh NAME
.Nm storectl
.Nd control stored daemon
.Sh SYNOPSIS
.Nm
.Op Fl V | -blah
.Pp
.Sh DESCRIPTION
.Pp
Lorem
.Nm 
Lorem ipsum.
.Nm
Lorem ipsum.
.Sh SEE ALSO
.Pp
.Xr stored 8 .
.Pp
.Sh AUTHORS
.Pp
.Ss This page
.An Artur Augustyniak(current)
.Pp
.Ss Software
.An Artur Augustyniak (Code Maintainer)
.Pp
.Ss Contributors
.Pp
Blah!

