#define DEFAULT_NOTIFICATION_CAPACITY 12

#define AUTO_CHECK_INTERVAL 120 * 1000

#define FREE_PERCENT_NOTICE 30

#define FREE_PERCENT_WARN 15

#define FREE_PERCENT_CRIT 5

#define SERVER_ENABLED 0

#define SERVER_PORT 1531

#define BIND_ADDR "127.0.0.1"