//#define IS_DAEMON

#define HAVE_SYSTEMD

#define AUTO_CHECK_INTERVAL 10 * 1000

#define DEFAULT_NOTIFICATION_CAPACITY 12

#define FREE_PERCENT_NOTICE 30

#define FREE_PERCENT_WARN 15

#define FREE_PERCENT_CRIT 5

#define SERVER_PORT 8081
